/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pjanof_cache_utilities_FileDateUtil */

#ifndef _Included_com_pjanof_cache_utilities_FileDateUtil
#define _Included_com_pjanof_cache_utilities_FileDateUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pjanof_cache_utilities_FileDateUtil
 * Method:    getLastAccessDate
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pjanof_cache_utilities_FileDateUtil_getLastAccessDate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_pjanof_cache_utilities_FileDateUtil
 * Method:    getLastModifiedDate
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pjanof_cache_utilities_FileDateUtil_getLastModifiedDate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_pjanof_cache_utilities_FileDateUtil
 * Method:    getLastStatusChangedDate
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pjanof_cache_utilities_FileDateUtil_getLastStatusChangedDate
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
